### ISSUE TITLE
Adopt a coding standard for the project

### ISSUE THREAD

**Issue by ariskataoka** [Automattic/vip-go-ci#230]
Currently, the vip-go-ci project doesn't follow any Coding Standards. 

Adopting a Coding Standard could bring benefits as:

- Improve the project's maintainability; 
- Improve the project's readability;
- Follow community agreed guidelines;
- Make the code cleaner;
- Every developer working on the project will follow the pre-defined styles;

For testing porpuses, I've applied two different coding standards in the project:

- PSR Coding Standards. [PR here](https://github.com/Automattic/vip-go-ci/pull/224);
- WordPress Coding Standards. [PR here](https://github.com/Automattic/vip-go-ci/pull/225);

Between the two options above, I would suggest PSR-12. Why?

- PSR is the most popular standard for projects written in pure PHP large frameworks, and several PHP developers in the community know it or have worked with that;
- Although this project's main functionality is to scan and analyze WordPress projects, the vip-go-ci project itself is not part of a WordPress plugin, a WordPress theme, nor meant to live inside WordPress projects;

**Comment by gudmdharalds** [comment]
Hi!

Thanks for opening up this issue. I completely agree about the benefits of a coding standard.

We discussed this in the new team (@Automattic/vip-quality) during our meeting, and we feel that this project should adopt the `WordPress` standard. The reasons are:

* This is most well known standard within the organization and knowledge of this standard is widespread.
* This standard is highly recommended. We do not want to be the only project using a different standard. 
* Any projects can use the `WordPress` standard, even though they are not WordPress projects.

There is nothing wrong with the PSR standard, we just do not think it is appropriate for this project due to the current culture and traditions. 

We feel that if there should be a change towards a different standard, that needs to be discussed among the VIP team more broadly and agreed on beforehand. 

Next week I intend to review and merge #225.
